title: Data Voyage - Blog of Holger Peters
email: email@holger-peters.de
description: > # this means to ignore newlines until "baseurl:"
    A personal blog on all things data-science and software
    engineering, with the occasional endeavours in functional
    programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.holger-peters.de"
twitter_username: data_hope
github_username:  HolgerPeters

# Build settings
markdown: kramdown
